name: nodejam CI

# Triggers the workflow on push or pull request events
on: [push, pull_request]

#on:
#  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master

defaults:
  run:
    working-directory: .

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots install
      - name: 'Tar files'
        run: tar -cvf app.tar target/*.jar
      - uses: actions/upload-artifact@v2
        with:
          name: app
          path: app.tar

  docker:
    name: docker ms-cloud-config
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      # share artifact across jobs
      - uses: actions/download-artifact@v2
        with:
          name: app
      - name: 'Untar files'
        run: mkdir -p target && tar -xvf app.tar target
      # build + push docker img
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0
      - name: Login to DockerHub
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.ECR_USERNAME }}
          password: ${{ secrets.ECR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          push: true
#          tags: 441604169807.dkr.ecr.eu-west-1.amazonaws.com/notejam:${{ github.sha }},441604169807.dkr.ecr.eu-west-1.amazonaws.com/notejam:latest
          tags: 441604169807.dkr.ecr.eu-west-1.amazonaws.com/notejam:latest